version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: IHAZUnicorn
  phpmyadmin:
    links:
      - mysql
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: IHAZUnicorn
    volumes:
      - /sessions
  apache:
    image: php:7.1.20-apache
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
      - ./logs/apache:/var/log/apache2
